"""Unified position/portfolio accounting for equities and options.

Cash, cost basis, realized/unrealized P&L, exposures, and net Greeks are all
tracked here. The same class serves the live paper account mirror, per-sleeve
sub-portfolios, and the backtester — one accounting implementation, tested once.

Conventions (see instruments.py): prices are per-share; notional = price * qty
* multiplier. ``qty`` on a Position is SIGNED (negative = short). ``realized_pnl``
is price-based (excludes commissions/fees); friction is tracked separately in
``total_costs`` and is already reflected in ``cash``, so ``equity()`` is always
net of all costs.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Callable, Optional

from quantfund.core.greeks import Greeks, bs_greeks, implied_vol
from quantfund.core.instruments import AssetClass, Equity, Instrument, Option
from quantfund.core.orders import Fill
from quantfund.core.snapshot import MarketSnapshot


@dataclass
class Position:
    instrument: Instrument
    qty: float = 0.0                 # signed; shares or contracts
    avg_cost: float = 0.0            # per share
    realized_pnl: float = 0.0        # price-based, cumulative, in dollars
    mark: Optional[float] = None     # per-share mark price
    mark_ts: Optional[datetime] = None
    greeks: Optional[Greeks] = None  # per-share greeks at last mark (options)
    underlying_mark: Optional[float] = None  # last underlying price (options)

    @property
    def is_open(self) -> bool:
        return abs(self.qty) > 1e-12

    @property
    def multiplier(self) -> int:
        return self.instrument.multiplier

    @property
    def market_value(self) -> float:
        """Signed liquidation value at the current mark (0 if never marked)."""
        price = self.mark if self.mark is not None else self.avg_cost
        return price * self.qty * self.multiplier

    @property
    def notional(self) -> float:
        return abs(self.market_value)

    @property
    def unrealized_pnl(self) -> float:
        if not self.is_open or self.mark is None:
            return 0.0
        return (self.mark - self.avg_cost) * self.qty * self.multiplier

    def apply_fill(self, fill: Fill) -> float:
        """Update qty/avg_cost, return realized P&L generated by this fill."""
        signed = fill.side.sign * fill.qty
        realized = 0.0
        if self.qty == 0 or (self.qty > 0) == (signed > 0):
            # opening or adding: weighted-average cost basis
            total = abs(self.qty) + fill.qty
            self.avg_cost = (abs(self.qty) * self.avg_cost + fill.qty * fill.price) / total
            self.qty += signed
        else:
            closing = min(abs(signed), abs(self.qty))
            direction = 1.0 if self.qty > 0 else -1.0
            realized = (fill.price - self.avg_cost) * closing * direction * self.multiplier
            self.realized_pnl += realized
            remaining = abs(signed) - closing
            self.qty += signed
            if remaining > 0:
                # flipped through zero: leftover opens at the fill price
                self.avg_cost = fill.price
            elif abs(self.qty) < 1e-12:
                self.qty = 0.0
                self.avg_cost = 0.0
        return realized


@dataclass(frozen=True)
class PortfolioGreeks:
    """Portfolio-level risk in dollar terms.

    dollar_delta: $ P&L per +100% move of each underlying, summed (equity qty*px
                  counts as delta 1). This equals net directional notional.
    gamma_shares: change in share-equivalent delta per $1 underlying move.
    theta_per_day: $ per calendar day from option decay.
    vega: $ per +1 vol point across all options.
    """

    dollar_delta: float = 0.0
    gamma_shares: float = 0.0
    theta_per_day: float = 0.0
    vega: float = 0.0


@dataclass
class Portfolio:
    cash: float
    starting_equity: float = 0.0
    positions: dict[str, Position] = field(default_factory=dict)
    total_costs: float = 0.0            # cumulative commissions + fees + slippage
    total_commissions_fees: float = 0.0  # cash costs only (already out of cash)
    day_anchor_equity: Optional[float] = None
    peak_equity: float = 0.0

    def __post_init__(self) -> None:
        if self.starting_equity == 0.0:
            self.starting_equity = self.cash
        self.peak_equity = max(self.peak_equity, self.cash)

    # ── trade application ────────────────────────────────────────────────

    def apply_fill(self, fill: Fill) -> float:
        """Apply a fill: cash moves by fill.cash_flow, position updates.
        Returns realized P&L from this fill (price-based)."""
        pos = self.positions.get(fill.instrument.key)
        if pos is None:
            pos = Position(instrument=fill.instrument)
            self.positions[fill.instrument.key] = pos
        realized = pos.apply_fill(fill)
        self.cash += fill.cash_flow
        self.total_commissions_fees += fill.commission + fill.fees
        self.total_costs += fill.total_friction
        # keep the mark current so equity() doesn't jump on the next mark
        pos.mark = fill.price
        pos.mark_ts = fill.ts
        return realized

    # ── marking ──────────────────────────────────────────────────────────

    def mark_position(self, key: str, price: float, ts: datetime,
                      greeks: Optional[Greeks] = None,
                      underlying_price: Optional[float] = None) -> None:
        pos = self.positions.get(key)
        if pos is None:
            return
        pos.mark = price
        pos.mark_ts = ts
        if greeks is not None:
            pos.greeks = greeks
        if underlying_price is not None:
            pos.underlying_mark = underlying_price

    def mark_from_snapshot(self, snapshot: MarketSnapshot, risk_free: float = 0.04) -> None:
        """Mark every open position from a point-in-time snapshot.

        Options are priced off the chain (bid/ask mid for marking; execution uses
        the cost model, never mid). Greeks come from the chain when present,
        else Black-Scholes off chain IV, else IV implied from the quote itself.
        """
        for pos in self.positions.values():
            if not pos.is_open:
                continue
            inst = pos.instrument
            if isinstance(inst, Equity):
                price = snapshot.last_price(inst.symbol)
                if price is not None:
                    self.mark_position(inst.key, price, snapshot.as_of)
            elif isinstance(inst, Option):
                chain = snapshot.get_option_chain(inst.underlying_symbol)
                under_px = snapshot.last_price(inst.underlying_symbol)
                if chain is None:
                    # No chain in view: decay-free fallback — BS off last known IV
                    if under_px is not None and pos.greeks is not None:
                        pass  # keep previous mark; do not invent prices
                    continue
                oq = next(
                    (q for q in chain.quotes if q.instrument.symbol == inst.symbol), None
                )
                if oq is None:
                    continue
                price = oq.quote.mid
                if price <= 0:
                    continue
                under_px = under_px if under_px is not None else chain.underlying_price
                greeks = oq.greeks
                if greeks is None and under_px and under_px > 0:
                    t = inst.years_to_expiration(snapshot.as_of)
                    iv = oq.iv
                    if iv is None:
                        iv = implied_vol(inst.right, price, under_px, inst.strike, t, risk_free)
                    if iv is not None and t > 0:
                        greeks = bs_greeks(inst.right, under_px, inst.strike, t, iv, risk_free)
                self.mark_position(inst.key, price, snapshot.as_of, greeks=greeks,
                                   underlying_price=under_px)
        self.peak_equity = max(self.peak_equity, self.equity())

    # ── valuation & risk ─────────────────────────────────────────────────

    def equity(self) -> float:
        return self.cash + sum(p.market_value for p in self.positions.values() if p.is_open)

    def market_value(self) -> float:
        return sum(p.market_value for p in self.positions.values() if p.is_open)

    def gross_exposure(self) -> float:
        return sum(p.notional for p in self.positions.values() if p.is_open)

    def net_exposure(self) -> float:
        return sum(p.market_value for p in self.positions.values() if p.is_open)

    def leverage(self) -> float:
        eq = self.equity()
        return self.gross_exposure() / eq if eq > 0 else float("inf")

    @property
    def buying_power(self) -> float:
        """Cash-account semantics for v0: uncommitted cash. No margin."""
        return max(0.0, self.cash)

    def exposure_by_underlying(self) -> dict[str, float]:
        out: dict[str, float] = {}
        for p in self.positions.values():
            if not p.is_open:
                continue
            u = p.instrument.underlying
            if isinstance(p.instrument, Option):
                # directional exposure of an option = |delta| notional when known
                if p.greeks is not None and p.underlying_mark:
                    expo = p.greeks.delta * p.qty * p.multiplier * p.underlying_mark
                else:
                    expo = p.market_value
            else:
                expo = p.market_value
            out[u] = out.get(u, 0.0) + expo
        return out

    def exposure_by_sector(self, sector_of: Callable[[str], str]) -> dict[str, float]:
        out: dict[str, float] = {}
        for underlying, expo in self.exposure_by_underlying().items():
            sector = sector_of(underlying)
            out[sector] = out.get(sector, 0.0) + expo
        return out

    def net_greeks(self) -> PortfolioGreeks:
        dollar_delta = 0.0
        gamma_shares = 0.0
        theta = 0.0
        vega = 0.0
        for p in self.positions.values():
            if not p.is_open:
                continue
            if isinstance(p.instrument, Equity):
                price = p.mark if p.mark is not None else p.avg_cost
                dollar_delta += p.qty * price
            elif isinstance(p.instrument, Option):
                if p.greeks is None:
                    continue
                mult = p.qty * p.multiplier
                under = p.underlying_mark or 0.0
                dollar_delta += p.greeks.delta * mult * under
                gamma_shares += p.greeks.gamma * mult
                theta += p.greeks.theta * mult
                vega += p.greeks.vega * mult
        return PortfolioGreeks(
            dollar_delta=dollar_delta, gamma_shares=gamma_shares,
            theta_per_day=theta, vega=vega,
        )

    # ── P&L ──────────────────────────────────────────────────────────────

    def realized_pnl(self) -> float:
        return sum(p.realized_pnl for p in self.positions.values())

    def unrealized_pnl(self) -> float:
        return sum(p.unrealized_pnl for p in self.positions.values() if p.is_open)

    def total_pnl(self) -> float:
        """Net of ALL costs: simply equity vs starting equity."""
        return self.equity() - self.starting_equity

    def start_new_day(self) -> None:
        self.day_anchor_equity = self.equity()

    def day_pnl(self) -> float:
        if self.day_anchor_equity is None:
            return 0.0
        return self.equity() - self.day_anchor_equity

    def drawdown(self) -> float:
        """Current drawdown fraction from peak equity (0 = at peak)."""
        if self.peak_equity <= 0:
            return 0.0
        return max(0.0, 1.0 - self.equity() / self.peak_equity)

    def open_positions(self) -> list[Position]:
        return [p for p in self.positions.values() if p.is_open]
